service: golang-simple-http-endpoint

frameworkVersion: "3"

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

plugins:
  - serverless-google-cloudfunctions
  - serverless-offline


# The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
# https://serverless.com/framework/docs/providers/google/guide/credentials/
#
# NOTE: the golang runtime is currently in alpha state, you must have access from google to use the alpha toolchain
provider:
  name: google
  runtime: go111                           # currently both vendored and go.mod repos are supported
  project: <YOUR_PROJECT_ID>                    # replace with your project name here
  credentials: <YOUR_CREDENTIALS_PATH> # path must be absolute, change to whichever keyfile you need

functions:
  hello:
    handler: Hello
    events:
      - http: path